name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tateti-game:$(date +%s)

    # Save the Docker image as a .tar file
    - name: Save Docker image to file
      run: docker save tateti-game:$(date +%s) -o tateti-game.tar

    # Upload the .tar file as an artifact
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: tateti-game.tar
