name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        IMAGE_TAG=tateti-game:latest
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "Built Docker image with tag: $IMAGE_TAG"

    - name: List Docker images
      run: docker images

    - name: Save Docker image to file
      run: |
        IMAGE_TAG=tateti-game:latest
        docker save $IMAGE_TAG -o tateti-game.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: tateti-game.tar
